# Generated by Django 2.2.16 on 2022-08-31 02:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article_Comment',
                'verbose_name_plural': 'Article_Comments',
                'db_table': 'article_comments',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '공지사항'), ('2', '이벤트'), ('3', '베스트'), ('4', '파트너찾기'), ('5', '토크')], max_length=5)),
                ('title', models.CharField(default='untitled', max_length=50)),
                ('text', models.TextField()),
                ('n_hit', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElasticInfos',
            fields=[
                ('tag', models.CharField(help_text='식별가능한 문자열', max_length=10, primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to=core.models.custom_info_path)),
                ('video', models.FileField(null=True, upload_to=core.models.custom_info_path)),
                ('info', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField()),
                ('category', models.CharField(choices=[('1', '작사/작곡/편곡'), ('2', '회화/공예'), ('3', '애니메이션/웹툰'), ('4', '경제/학술'), ('5', '기타')], default='5', max_length=1)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='OrderArtists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(blank=True, default=False)),
                ('deliver_detail', models.IntegerField(blank=True, choices=[(0, '0단계'), (1, '1단계'), (2, '2단계'), (3, '3단계'), (4, '4단계')], default=0)),
                ('discount_price', models.IntegerField(blank=True, default=100000, null=True)),
                ('price', models.IntegerField(blank=True, default=100000)),
                ('music_purpose', models.IntegerField(choices=[(1, '선물용'), (2, '연습용')])),
                ('music_name', models.CharField(max_length=20)),
                ('music_vibe', models.CharField(blank=True, max_length=100)),
                ('music_ref', models.CharField(blank=True, max_length=20)),
                ('music_receiver', models.CharField(blank=True, max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'OrderArtist',
                'verbose_name_plural': 'OrderArtists',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(blank=True, default=False)),
                ('deliver_detail', models.IntegerField(blank=True, choices=[(0, '0단계'), (1, '1단계'), (2, '2단계'), (3, '3단계'), (4, '4단계')], default=0)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, default=100000)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItems',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_code', models.CharField(max_length=20)),
                ('ordered_date', models.DateTimeField(null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('PG', models.CharField(choices=[('K', '카카오페이'), ('N', '네이버페이'), ('T', '토스'), ('C', '카드결제'), ('ETC', '무통장입금')], default='XXX', max_length=3)),
                ('pre_request', models.CharField(blank=True, max_length=100, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField()),
                ('password', models.CharField(blank=True, default='PLAYPLZ', max_length=10, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OrderVideo',
                'verbose_name_plural': 'OrderVideos',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Posts',
                'ordering': ['-pk'],
            },
        ),
    ]
