# Generated by Django 2.2.16 on 2022-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220908_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdfundingorderitem',
            name='deliver_detail',
            field=models.IntegerField(blank=True, choices=[(1, '1단계'), (2, '2단계'), (3, '3단계'), (4, '4단계')], default=1),
        ),
        migrations.AlterField(
            model_name='openfundingorderitem',
            name='deliver_detail',
            field=models.IntegerField(blank=True, choices=[(1, '1단계'), (2, '2단계'), (3, '3단계'), (4, '4단계')], default=1),
        ),
        migrations.AlterField(
            model_name='secretfundingorderitem',
            name='deliver_detail',
            field=models.IntegerField(blank=True, choices=[(1, '1단계'), (2, '2단계'), (3, '3단계'), (4, '4단계')], default=1),
        ),
    ]
