# Generated by Django 2.2.16 on 2022-09-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220909_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
