# Generated by Django 2.2.16 on 2022-09-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220910_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
