# Generated by Django 2.2.16 on 2022-09-22 19:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220913_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='refund_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='refund_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_orderitem_path),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='refund_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='refund_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_orderitem_path),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='refund_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='refund_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.custom_orderitem_path),
        ),
    ]
