# Generated by Django 2.2.16 on 2022-09-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220922_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
