# Generated by Django 2.2.16 on 2022-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_articles_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdfundingorderitem',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='openfundingorderitem',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='secretfundingorderitem',
            name='ref_code',
        ),
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='vbank_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='vbank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='vbank_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='vbank_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='vbank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='vbank_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='imp_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='vbank_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='vbank_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='vbank_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
