# Generated by Django 2.2.16 on 2022-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221209_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='ref_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
