# Generated by Django 2.2.16 on 2022-12-19 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_auto_20221216_1601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20221214_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.RemoveField(
            model_name='crowdfundingorderitem',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='openfundingorderitem',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='secretfundingorderitem',
            name='PG',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='placement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auction.Placement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crowdfundingorderitem',
            name='vbank_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openfundingorderitem',
            name='vbank_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='secretfundingorderitem',
            name='vbank_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('PG', models.CharField(choices=[('D', '다날'), ('T', '토스페이'), ('KG', 'KG이니시스'), ('N', '네이버페이'), ('KA', '카카오페이'), ('ETC', '기타')], default='D', max_length=3)),
                ('imp_uid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pay_method', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('vbank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vbank_num', models.CharField(blank=True, max_length=100, null=True)),
                ('vbank_date', models.CharField(blank=True, max_length=100, null=True)),
                ('card_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_url', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crowdfundingorderitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment'),
        ),
        migrations.AddField(
            model_name='openfundingorderitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment'),
        ),
        migrations.AddField(
            model_name='secretfundingorderitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment'),
        ),
    ]
