# Generated by Django 2.2.16 on 2022-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20221219_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='sex', max_length=100),
            preserve_default=False,
        ),
    ]
