# Generated by Django 2.2.16 on 2023-01-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20221220_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crowdfundingorderitem',
            options={'ordering': ['updated'], 'verbose_name': '일반티켓 주문', 'verbose_name_plural': '일반티켓 주문들'},
        ),
        migrations.AlterModelOptions(
            name='secretfundingorderitem',
            options={'ordering': ['updated'], 'verbose_name': '경쟁티켓 주문', 'verbose_name_plural': '경쟁티켓 주문들'},
        ),
    ]
