# Generated by Django 2.2.16 on 2023-01-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230104_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['user'], 'verbose_name': '결제정보', 'verbose_name_plural': '결제정보들'},
        ),
    ]
