# Generated by Django 2.2.16 on 2023-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0036_auto_20230119_1646'),
        ('core', '0025_kakao_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('1', '공지사항'), ('2', '이벤트'), ('3', '보도자료'), ('4', '참고자료'), ('5', '요청사항')], max_length=5),
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='placement',
        ),
        migrations.AddField(
            model_name='coupon',
            name='placement',
            field=models.ManyToManyField(to='auction.Placement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PG',
            field=models.CharField(choices=[('D', '다날'), ('T', '토스페이'), ('KG', 'KG이니시스'), ('N', '네이버페이'), ('KA', '카카오페이'), ('ETC', '기타')], default='T', max_length=3),
        ),
    ]
