# Generated by Django 2.2.16 on 2023-02-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20230127_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('1', '공지사항'), ('2', '이벤트'), ('3', '보도자료'), ('4', '참고자료'), ('5', '특별기획')], max_length=5),
        ),
    ]
