# Generated by Django 2.2.16 on 2023-03-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_articles_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-updated'], 'verbose_name': '쿠폰', 'verbose_name_plural': '쿠폰들'},
        ),
        migrations.AlterModelOptions(
            name='crowdfundingorderitem',
            options={'verbose_name': '일반티켓 주문', 'verbose_name_plural': '일반티켓 주문들'},
        ),
        migrations.AlterModelOptions(
            name='openfundingorderitem',
            options={'verbose_name': '오픈 펀딩 주문', 'verbose_name_plural': '오픈 펀딩 주문들'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ['-updated'], 'verbose_name': '응답지', 'verbose_name_plural': '응답지들'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'ordering': ['-updated'], 'verbose_name': '설문지', 'verbose_name_plural': '설문지들'},
        ),
        migrations.AlterModelOptions(
            name='secretfundingorderitem',
            options={'verbose_name': '경쟁티켓 주문', 'verbose_name_plural': '경쟁티켓 주문들'},
        ),
    ]
