# Generated by Django 2.2.16 on 2023-04-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20230305_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_soldout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='short_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
