# Generated by Django 2.2.16 on 2023-07-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20230521_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='display_url',
            field=models.TextField(blank=True, default='https://m.trevari.co.kr/categories/5', null=True),
        ),
    ]
