# Generated by Django 2.2.16 on 2022-09-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20220908_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='d_place',
            field=models.CharField(blank=True, help_text='만남 장소', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_1',
            field=models.TextField(blank=True, help_text='펀딩상세 1', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_1_title',
            field=models.TextField(blank=True, help_text='펀딩상세 1 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_2',
            field=models.TextField(blank=True, help_text='펀딩상세 2', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_2_title',
            field=models.TextField(blank=True, help_text='펀딩상세 2 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_3',
            field=models.TextField(blank=True, help_text='펀딩상세 3', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_3_title',
            field=models.TextField(blank=True, help_text='펀딩상세 3 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='duration',
            field=models.CharField(blank=True, help_text='만남 시간', max_length=50, null=True),
        ),
    ]
