# Generated by Django 2.2.16 on 2022-09-14 11:29

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auto_20220908_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementmemory',
            name='history_image',
        ),
        migrations.AddField(
            model_name='placementmemory',
            name='history_sign',
            field=models.ImageField(help_text='Remember Sign', null=True, upload_to=auction.models.custom_remember_image_path),
        ),
    ]
