# Generated by Django 2.2.16 on 2022-10-04 01:23

import auction.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auto_20220919_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='detail_4',
            field=models.TextField(blank=True, help_text='펀딩상세 4', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='detail_4_title',
            field=models.TextField(blank=True, help_text='펀딩상세 4 타이틀', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='detail_5',
            field=models.TextField(blank=True, help_text='펀딩상세 5', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='detail_5_title',
            field=models.TextField(blank=True, help_text='펀딩상세 5 타이틀', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='detail_6',
            field=models.TextField(blank=True, help_text='펀딩상세 6', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='detail_6_title',
            field=models.TextField(blank=True, help_text='펀딩상세 6 타이틀', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='image_4',
            field=models.ImageField(blank=True, help_text='상품 설명 이미지 4', null=True, upload_to=auction.models.custom_etc_path),
        ),
        migrations.CreateModel(
            name='TimeStoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='TimeStore Thumbnail Image', null=True, upload_to='')),
                ('title', models.TextField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction.Placement')),
            ],
            options={
                'verbose_name': '굿즈',
                'verbose_name_plural': '굿즈들',
                'ordering': ['-id'],
            },
        ),
    ]
