# Generated by Django 2.2.16 on 2022-10-04 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auto_20221004_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionartist',
            options={'ordering': ['-created'], 'verbose_name': '옥션 아티스트', 'verbose_name_plural': '옥션 아티스트들'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['placement', '-updated'], 'verbose_name': '크라우드 펀딩객체', 'verbose_name_plural': '크라우드 펀딩객체들'},
        ),
        migrations.AlterModelOptions(
            name='oney',
            options={'ordering': ['-created'], 'verbose_name': '기록 워니', 'verbose_name_plural': '기록 워니들'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['-placement_order'], 'verbose_name': '옥션상품', 'verbose_name_plural': '옥션상품들'},
        ),
        migrations.AlterModelOptions(
            name='placementbid',
            options={'ordering': ['placement', '-offer'], 'verbose_name': '응찰객체', 'verbose_name_plural': '응찰객체들'},
        ),
        migrations.AlterModelOptions(
            name='placementmemory',
            options={'ordering': ['-created'], 'verbose_name': '옥션기록', 'verbose_name_plural': '옥션기록들'},
        ),
        migrations.AddField(
            model_name='auctionartist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionartist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
