# Generated by Django 2.2.16 on 2022-10-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_auto_20221004_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionauthorization',
            options={'ordering': ['-user'], 'verbose_name': '옥션 권한객체', 'verbose_name_plural': '옥션 권한객체들'},
        ),
        migrations.AlterModelOptions(
            name='auctionnfttoken',
            options={'ordering': ['-id'], 'verbose_name': 'NFT 토큰', 'verbose_name_plural': 'NFT 토큰들'},
        ),
        migrations.AlterModelOptions(
            name='autobid',
            options={'ordering': ['-created'], 'verbose_name': '자동응찰', 'verbose_name_plural': '자동응찰들'},
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_order',
            field=models.IntegerField(default=1, help_text='음수: 종료, 1 < : 진행중, 1:예정, 0:가리기'),
        ),
    ]
