# Generated by Django 2.2.16 on 2022-10-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auto_20221018_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='etc_1',
        ),
    ]
