# Generated by Django 2.2.16 on 2022-10-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_remove_placement_etc_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestoreitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timestoreitem',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction.Placement'),
        ),
    ]
