# Generated by Django 2.2.16 on 2022-10-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auto_20221020_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestoreitem',
            name='background',
            field=models.ImageField(blank=True, help_text='TimeStore Background Image', null=True, upload_to=''),
        ),
    ]
