# Generated by Django 2.2.16 on 2022-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_timestoreitem_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestoreitem',
            name='background',
            field=models.ImageField(default='df', help_text='TimeStore Background Image', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timestoreitem',
            name='description',
            field=models.TextField(default='wfewf', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timestoreitem',
            name='image',
            field=models.ImageField(default='efef', help_text='TimeStore Thumbnail Image', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timestoreitem',
            name='title',
            field=models.TextField(default='efef', max_length=50),
            preserve_default=False,
        ),
    ]
