# Generated by Django 2.2.16 on 2022-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_auto_20221028_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestoreitem',
            name='is_soldout',
            field=models.BooleanField(default=False),
        ),
    ]
