# Generated by Django 2.2.16 on 2022-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_timestoreitem_is_soldout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oney',
            name='comment',
            field=models.CharField(help_text='워니의 코멘트를 입력해주세요', max_length=85),
        ),
        migrations.AlterField(
            model_name='placementmemory',
            name='celeb_comment',
            field=models.CharField(help_text='셀럽의 코멘트를 입력해주세요', max_length=85),
        ),
    ]
