# Generated by Django 2.2.16 on 2022-11-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0018_auto_20221117_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='etc_1',
            field=models.TextField(blank=True, help_text='기타정보1', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='etc_1_on',
            field=models.BooleanField(default=False, help_text='기타정보1 활성화'),
        ),
        migrations.AddField(
            model_name='placement',
            name='etc_2',
            field=models.TextField(blank=True, help_text='기타정보2', null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='etc_2_on',
            field=models.BooleanField(default=False, help_text='기타정보2 활성화'),
        ),
    ]
