# Generated by Django 2.2.16 on 2022-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0019_auto_20221123_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='rep',
            field=models.CharField(blank=True, help_text='회차 정보', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.CharField(choices=[('crowdfunding', '공동구매'), ('openfunding', '경쟁구매'), ('secretfunding', '단독구매')], default='openfunding', help_text='경매 종류', max_length=20),
        ),
    ]
