# Generated by Django 2.2.16 on 2022-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0022_auto_20221209_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestoreitem',
            name='is_col',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placement',
            name='placement_type',
            field=models.CharField(choices=[('crowdfunding', '일반구매'), ('secretfunding', '경쟁구매'), ('openfunding', '경매')], default='crowdfunding', help_text='경매 종류', max_length=20),
        ),
    ]
