# Generated by Django 2.2.16 on 2022-12-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0024_auto_20221214_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='description',
            field=models.TextField(help_text='설명', max_length=400),
        ),
        migrations.AlterField(
            model_name='placement',
            name='title',
            field=models.CharField(help_text='제목', max_length=50),
        ),
    ]
