# Generated by Django 2.2.16 on 2022-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0025_auto_20221214_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='title',
            field=models.TextField(help_text='제목', max_length=50),
        ),
    ]
