# Generated by Django 2.2.16 on 2022-12-20 12:44

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0026_auto_20221216_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='image_1',
            field=models.ImageField(blank=True, default='static_root/rev/img/common/logo_image.png', help_text='상품 설명 이미지 1', null=True, upload_to=auction.models.custom_etc_path),
        ),
    ]
