# Generated by Django 2.2.16 on 2022-12-20 12:49

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0027_auto_20221220_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='image_1',
            field=models.ImageField(blank=True, default='인스타그램_프로필용.png', help_text='상품 설명 이미지 1', null=True, upload_to=auction.models.custom_etc_path),
        ),
    ]
