# Generated by Django 2.2.16 on 2022-12-20 14:02

import auction.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0028_auto_20221220_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='image_1',
            field=models.ImageField(blank=True, default='default.png', help_text='상품 설명 이미지 1', upload_to=auction.models.custom_etc_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='image_2',
            field=models.ImageField(blank=True, default='default.png', help_text='상품 설명 이미지 2', upload_to=auction.models.custom_etc_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='image_3',
            field=models.ImageField(blank=True, default='default.png', help_text='상품 설명 이미지 3', upload_to=auction.models.custom_etc_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='image_4',
            field=models.ImageField(blank=True, default='default.png', help_text='상품 설명 이미지 4', upload_to=auction.models.custom_etc_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='m_banner_video_mp4',
            field=models.FileField(blank=True, default='default.mp4', help_text='Mobile mp4 VIDEO', upload_to=auction.models.custom_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='placement',
            name='pc_banner_video_mp4',
            field=models.FileField(blank=True, default='default.mp4', help_text='PC mp4 VIDEO', upload_to=auction.models.custom_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='placement',
            name='secret_video',
            field=models.FileField(blank=True, default='default.mp4', help_text='Unboxing list video', upload_to=auction.models.custom_video_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', help_text='Thumbnail Image', upload_to=auction.models.custom_etc_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='unboxing_video_mp4',
            field=models.FileField(blank=True, default='default.mp4', help_text='Unboxing list video', upload_to=auction.models.custom_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
