# Generated by Django 2.2.16 on 2022-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0031_auto_20221220_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionartist',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', help_text='Auction 아티스트 이미지', upload_to='Auction/avatar/'),
        ),
    ]
