# Generated by Django 2.2.16 on 2023-01-04 18:03

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0032_auto_20221220_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='image_5',
            field=models.ImageField(blank=True, default='default.png', help_text='상품 설명 이미지 4', upload_to=auction.models.custom_etc_path),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_1',
            field=models.TextField(blank=True, help_text='에디터 설명', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_1_title',
            field=models.TextField(blank=True, default='에디터 노트', help_text='에디터 제목', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_2',
            field=models.TextField(blank=True, help_text='상품상세 2', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_2_title',
            field=models.TextField(blank=True, help_text='상품상세 2 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_3',
            field=models.TextField(blank=True, help_text='상품상세 3', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_3_title',
            field=models.TextField(blank=True, help_text='상품상세 3 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_4',
            field=models.TextField(blank=True, help_text='상품상세 4', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_4_title',
            field=models.TextField(blank=True, help_text='상품상세 4 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_5',
            field=models.TextField(blank=True, help_text='상품상세 5', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_5_title',
            field=models.TextField(blank=True, help_text='상품상세 5 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_6',
            field=models.TextField(blank=True, help_text='상품상세 6', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='detail_6_title',
            field=models.TextField(blank=True, help_text='상품상세 6 타이틀', null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='unit_price',
            field=models.IntegerField(default=50000, help_text='일반티켓 가격 or 경쟁티켓 가격'),
        ),
    ]
