# Generated by Django 2.2.16 on 2023-01-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0033_auto_20230104_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='buy_limit',
            field=models.IntegerField(default=5, help_text='구매 제한 개수'),
        ),
    ]
