# Generated by Django 2.2.16 on 2023-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0034_placement_buy_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oney',
            name='comment',
            field=models.CharField(help_text='워니의 코멘트를 입력해주세요', max_length=500),
        ),
        migrations.AlterField(
            model_name='oney',
            name='name',
            field=models.CharField(help_text='워니의 성함을 입력해주세요', max_length=50),
        ),
        migrations.AlterField(
            model_name='placementmemory',
            name='celeb_comment',
            field=models.CharField(help_text='셀럽의 코멘트를 입력해주세요', max_length=500),
        ),
        migrations.AlterField(
            model_name='placementmemory',
            name='celeb_name',
            field=models.CharField(help_text='셀럽의 성함을 입력해주세요', max_length=50),
        ),
    ]
