# Generated by Django 2.2.16 on 2023-01-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0035_auto_20230110_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['placement', '-updated'], 'verbose_name': '일반티켓 펀딩객체', 'verbose_name_plural': '일반티켓 펀딩객체들'},
        ),
    ]
