# Generated by Django 2.2.16 on 2022-08-31 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ArtistProfile',
                'verbose_name_plural': 'ArtistProfiles',
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=False)),
                ('level', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold')], default='B', max_length=10)),
                ('credit', models.IntegerField(default=0, help_text='원앤온리 적립금')),
                ('K_name', models.CharField(max_length=15)),
                ('E_name', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, help_text='50x50 사이즈 작은 프로필이미지', upload_to='artist/images/')),
                ('bio_image', models.ImageField(blank=True, help_text='큰 프로필이미지', null=True, upload_to='artist/images/')),
                ('bio_video', models.FileField(blank=True, upload_to='artist/videos/')),
                ('bio_text', models.CharField(max_length=300)),
                ('instrument', models.CharField(choices=[('H', '현악기'), ('G', '관악기'), ('T', '타악기'), ('ETC', '기타')], max_length=3)),
                ('price', models.IntegerField(default=100000)),
                ('discount_price', models.IntegerField(blank=True, default=None, null=True)),
                ('lesson_price', models.IntegerField(default=200000)),
                ('lesson_discount_price', models.IntegerField(blank=True, default=None, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1 플플'), (2, '2 플플'), (3, '3 플플'), (4, '4 플플'), (5, '5 플플')], default=1)),
                ('text', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='artist.Artists')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-pk'],
            },
        ),
    ]
