# Generated by Django 2.2.16 on 2022-12-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20220831_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', help_text='50x50 사이즈 작은 프로필이미지', upload_to='artist/images/'),
        ),
    ]
