# Generated by Django 2.2.16 on 2022-08-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220831_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='uuid',
            field=models.CharField(default=12331, max_length=36),
            preserve_default=False,
        ),
    ]
