# Generated by Django 2.2.4 on 2022-09-19 14:59

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220908_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='핸드폰 번호', max_length=128, null=True, region=None),
        ),
    ]
