# Generated by Django 2.2.16 on 2022-09-26 16:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220919_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='관리자 핸드폰 번호', max_length=128, region=None)),
                ('activate', models.BooleanField(default=True, help_text='관리 알람 활성화')),
            ],
            options={
                'verbose_name': '관리자 번호',
                'verbose_name_plural': '관리자 번호들',
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprivacy',
            options={'ordering': ['-pk'], 'verbose_name': '워니 동의정보', 'verbose_name_plural': '워니 동의정보들'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ['-pk'], 'verbose_name': '워니', 'verbose_name_plural': '워니들'},
        ),
        migrations.AlterModelOptions(
            name='verification',
            options={'ordering': ['-pk'], 'verbose_name': '인증', 'verbose_name_plural': '인증들'},
        ),
    ]
